### ISSUE TITLE
Support nested hashes

### ISSUE THREAD

**Issue by izolate** [defunctzombie/form-serialize#11]
I've had no luck with getting the following to work:

```
<form>
  <input type='text' name='fruit[citrus][lemon]'>
  <input type='text' name='fruit[citrus][orange]'>
  <input type='text' name='fruit[citrus][lime]'>
</form>
```

__Desired output__
```
  fruit: {
    citrus: {
      lemon: $value,
      orange: $value,
      lime: $value
    }
  }
```

__Actual output__
```
  fruit: {
    citrus: {
      lime: $value
    }
  }
```

Before I start digging through the source to identify the problem, I thought I'd run it by here in case the cause is glaringly obvious to anybody.

**Comment by defunctzombie** [comment]
@phillipj and @jxson both worked on hash related serialization and likely have some input.

**Comment by jxson** [comment]
@izolate I think this is a bug, I can take a look in the next day or so.

**Comment by izolate** [comment]
thanks mate. looking forward to it

**Comment by izolate** [comment]
Found the root cause. Please see PR.
