### ISSUE TITLE
Bower support?

### ISSUE THREAD

**Issue by brettz9** [defunctzombie/form-serialize#20]
You willing to add Bower support? Helpful for Bower packages which use your library as a dependency...

**Comment by defunctzombie** [comment]
Not really interested since I just publish this to npm. I consider that the primary js package manager these days.

**Comment by brettz9** [comment]
In case anyone finds this issue, I've added my own copy (which also includes https://github.com/defunctzombie/form-serialize/pull/21 ) to the Bower registry under form-serialize.
