### ISSUE TITLE
Unable to have array of one value in nested objects

### ISSUE THREAD

**Issue by iqnivek** [defunctzombie/form-serialize#23]
A form with a single `<input type="hidden" name="user[tags][]" value="cow" />` is serialized as:
````
{
  user: {
    tags: "cow"
  }
}
```

I'd expect it to be serialized as:
```
{
  user: {
    "tags": ["cow"]
  }
}
```

There's no issue when there are multiple items in the array, this only happens when there's only one element.

**Comment by defunctzombie** [comment]
I think this issue is similar/related to https://github.com/defunctzombie/form-serialize/issues/18

**Comment by iqnivek** [comment]
yup, similar but a distinct situation.

**Comment by jxson** [comment]
@iqnivek @defunctzombie PR #25 should have closed this (I annotated the commit message wrong for it to happen automatically).

**Comment by foodgy** [comment]
Is there a way to serialize input like this <input type="text" name="tags[]" value="tag1, tag2"> into this ```tags: ["tag1", "tag2"]```?
