### ISSUE TITLE
Serialization not working for input with type file

### ISSUE THREAD

**Issue by mtakac** [defunctzombie/form-serialize#27]
Looks like the form serialization is not working for file type inputs. Not sure if this is a bug or a design decision, anyway I would like to use form-serialize in my app and I need file uploads so maybe I can take a look at the code base and issue a pull request adding the file type inputs serialization. Let me know if I can help.

**Comment by defunctzombie** [comment]
design decision. File inputs are not serialized the same way, the use form data uploads, etc. You can take a look but I am almost certain it is not something for this library to handle given how forms are handled in the browser

**Comment by ctf0** [comment]
@defunctzombie is it possible for file inputs with single file, if its an image the package serialize it as a data:uri ?

**Comment by kwent** [comment]
We could make an option to serialize images in `base64`. Most of JSON api accepts this format.
