### ISSUE TITLE
Can/should inputs without a `name` attribute be ignored?

### ISSUE THREAD

**Issue by greypants** [defunctzombie/form-serialize#39]
I have some form elements that are used to toggle other form fields with JS. 

Something like this:

```html
<select onChange={ toggleExtraFields }>
  <option value="foo" />
  <option value="bar" selected />
</select>
```

I don't want this field to be serialized, as it's only used to toggle UI. But currently, even though it has no name attribute, it gets serialized as:

```js
undefined: 'bar'
```

Do you see any problems with ignoring un-named inputs in the serialize method, or is that something worth adding? I'm happy to tackle that if so.

**Comment by defunctzombie** [comment]
Hm, how does the browser handle this? The goal of this module has historically been to deal with these fields in a manner similar to how a browser would handle active fields.

**Comment by greypants** [comment]
Looks like it ignores them (at least in Chrome): https://jsfiddle.net/xv5hmLq3/

```
<form>
  <input type="text" value="This should not show up"/>
  <input name="foo" value="Foo"/>
  <button>Submit</button>
</form>
```

serializes to 

```
?foo=NAMED%21
```

**Comment by defunctzombie** [comment]
Ok, can you make a PR with tests? I agree that having undefined as a key
doesn't make much sense.

**Comment by greypants** [comment]
Whelp, turns out the library already does this: 
https://github.com/defunctzombie/form-serialize/blob/master/index.js#L45-L47

My issue was that the input's name was the **string** `'undefined'`. Ignore me! Thanks for the great work on this library.
